import { Horseman } from "../types";

export const titles: Record<number, string[]> = {
  0: [
    "Bootstrap Template Enjoyer",
    "WordPress Theme Customizer",
    "w3schools Copy Paster",
    "Inspect Element Hacker",
    "Live Server Enthusiast",
    "HTML Email Table Maker",
    "jQuery Plugin Collector",
    "CSS Float Struggler",
    "Notepad++ Power User",
    "FTP Uploader Professional",
  ],
  10: [
    "create-react-app Survivor",
    "console.log Debugger",
    "Prettier Default Settings User",
    "GitHub Desktop Navigator",
    "Stackoverflow Lurker",
    "Frontend Tutorial Hoarder",
    "node_modules Disk Space Victim",
    "Chrome DevTools Tab Juggler",
    "Flexbox Froggy Graduate",
    "npm Script Copy-Paster",
  ],
  20: [
    "CSS Battle Participant",
    "npm Commands Memorizer",
    "Linux Mint Tourist",
    "AI Prompt Engineer",
    "Medium Article Speedrunner",
    "VSCode Extension Collector",
    "Docker Tutorial Bookmarker",
    "TypeScript any Abuser",
    "Codepen Demo Forker",
    "Documentation Skimmer",
  ],
  30: [
    "Tailwind Utility Hoarder",
    "Docker Container Collector",
    "Vim Tutorial Dropout",
    "Regex Pattern Apprentice",
    "Dark Theme Evangelizer",
    "State Management Overthinker",
    "Git Branch Naming Poet",
    "Kubernetes Yaml Copier",
    "React Hook Dependency Array Gambler",
    "Terminal Color Scheme Perfectionist",
  ],
  40: [
    "Framework Tier List Creator",
    "Mechanical Keyboard Cultist",
    "Git Rebase Survivor",
    "Notion Template Architect",
    "Leetcode Easy Grinder",
    "Type System Evangelist",
    "Eslint Rule Debater",
    "Side Project Cemetery Keeper",
    "API Authentication Specialist",
    "Database Migration Surgeon",
  ],
  50: [
    "Neovim Config Forker",
    "Zsh Theme Collector",
    "Monorepo Structure Theorist",
    "Terminal Rice Enthusiast",
    "Code Font Perfectionist",
    "Testing Pyramid Scholar",
    "Homebrew Formula Connoisseur",
    "CI Pipeline Artisan",
    "Performance Optimization Obsessor",
    "Custom Snippet Creator",
  ],
  60: [
    "Vim Macro Philosopher",
    "Arch Install Speedrunner",
    "Custom Kernel Builder",
    "Emacs Pinky Survivor",
    "Database Schema Poet",
    "WASM Module Compiler",
    "Infrastructure-as-Code Architect",
    "Functional Programming Purist",
    "Distributed System Theorist",
    "Legacy Code Archaeologist",
  ],
  70: [
    "Memory Leak Hunter",
    "Binary Size Optimizer",
    "Assembly Code Whisperer",
    "System Call Debugger",
    "Core Dump Analyzer",
    "Cache Invalidation Strategist",
    "Thread Synchronization Guru",
    "Compiler Optimization Tuner",
    "Zero-Copy Network Stack Developer",
    "Obscure Protocol Implementer",
  ],
  80: [
    "Tmux Session Hoarder",
    "NixOS Configuration Artist",
    "Gentoo Installation Guide Author",
    "Lambda Calculus Enjoyer",
    "Monkey Patch Specialist",
    "Custom DSL Designer",
    "Formal Verification Enthusiast",
    "Microcode Optimizer",
    "Operating System Kernel Contributor",
    "Asynchronous Runtime Architect",
  ],
  90: [
    "Kernel Patch Reviewer",
    "Custom Lisp Dialect Creator",
    "/dev/null Pipeline Architect",
    "Bare Metal Programmer",
    "Zero Dependency Purist",
    "Cryptographic Protocol Auditor",
    "CPU Architecture Theorist",
    "Network Stack Reimplementer",
    "Self-Hosting Everything Evangelist",
    "Hardware Description Language Artist",
  ],
  100: [
    "Bit Flip Philosopher",
    "Matrix Root Access Haver",
    "Time Complexity Denyer",
    "Quantum Bit Whisperer",
    "Unix Epoch Counter",
    "Compiler Compiler Writer",
    "Turing Complete CSS Demonstrator",
    "Hardware-Software Boundary Eraser",
    "Time-Space Complexity Transcender",
    "Computational Universe Theorist",
  ],
};

export const parameters: Horseman[] = [
  {
    title: "Tool Maximalism",
    description: "Captures the Arch/Neovim/setup obsession",
  },
  {
    title: "Brain Rot Level",
    description: "Measures pure unhinged energy",
  },
  {
    title: "Tech/Yap Balance",
    description: "The Yacine Factor™",
  },
  {
    title: "Language Opinions",
    description: "The Rust-to-normie pipeline",
  },
];
